# Generated by Django 5.1.3 on 2024-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heroDurability',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='heroSpeed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='heroStrength',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='maximumMoney',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
