# Generated by Django 5.1.2 on 2024-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_herodurability_user_herospeed_user_herostrength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosenLeague',
            field=models.IntegerField(default=1),
        ),
    ]
